<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <Using Include="Microsoft.AspNetCore.Builder" />
    <Using Include="Microsoft.AspNetCore.Http" />
    <Using Include="Microsoft.AspNetCore.Routing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Payments.Application/Payments.Application.csproj" />
  </ItemGroup>
</Project>
